# matrix
set -g status-style 'bg=#000000,fg=#00ff41'
set -g window-status-current-style 'fg=#66ff99,bold'
set -g window-status-style 'fg=#006622'
set -g message-style 'bg=#001a00,fg=#00ff41'
set -g message-command-style 'bg=#001a00,fg=#00cc33'
set -g pane-border-style 'fg=#006622'
set -g pane-active-border-style 'fg=#00ff41'
