# robotnik
set -g status-style 'bg=#0c0e14,fg=#d42020'
set -g window-status-current-style 'fg=#ff3838,bold'
set -g window-status-style 'fg=#7a1010'
set -g message-style 'bg=#161a24,fg=#d42020'
set -g message-command-style 'bg=#161a24,fg=#a01818'
set -g pane-border-style 'fg=#2a2e3a'
set -g pane-active-border-style 'fg=#d42020'
