# skynet
set -g status-style 'bg=#0a0000,fg=#ff3030'
set -g window-status-current-style 'fg=#ff6060,bold'
set -g window-status-style 'fg=#881515'
set -g message-style 'bg=#1a0808,fg=#ff3030'
set -g message-command-style 'bg=#1a0808,fg=#cc2020'
set -g pane-border-style 'fg=#551010'
set -g pane-active-border-style 'fg=#ff3030'
