# wayne-tech
set -g status-style 'bg=#080b12,fg=#a0b4cc'
set -g window-status-current-style 'fg=#e0eaf5,bold'
set -g window-status-style 'fg=#2a3a4a'
set -g message-style 'bg=#121a24,fg=#a0b4cc'
set -g message-command-style 'bg=#121a24,fg=#6a9fd8'
set -g pane-border-style 'fg=#2a3a4a'
set -g pane-active-border-style 'fg=#a0b4cc'
