# Yazi keymap overrides

[[mgr.prepend_keymap]]
on   = ["E"]
run  = '''shell 'dir="$@"; [ -f "$dir" ] && dir="$(dirname "$dir")"; tmux new-window -c "$dir" nvim' --confirm'''
desc = "Open new tmux window with Neovim in target directory"

[[mgr.prepend_keymap]]
on   = ["T"]
run  = '''shell 'dir="$@"; [ -f "$dir" ] && dir="$(dirname "$dir")"; tmux new-window -c "$dir"' --confirm'''
desc = "Open new tmux window in target directory"
